### PR TITLE
Algoritm

### PR DESCRIPTION
**Pull request by look4jesper**
Backend was merged into algoritm at 16:00 09/10/2018. 

Created classes SearchHandler and SearchHandlerTest.

Added method co2Saved to class Trip and method ratingChange to class User. Changed some attribute names in these classes (from what they were called in backed branch)  to match the code we had written in order for the program to compile.

SearchHandlerTest should be expanded with more tests, currently does not cover very many situations.

### CODE REVIEW

**Comment by jadlers** [comment]
Should this one be closed now @GustavHandmark ?

**Comment by look4jesper** [comment]
Since Gustav has merged our branch into backend then it seems unnessecary to merge both algoritm and backend into master imo.

**Comment by GustavHandmark** [comment]
@jadlers Yes, should be fine to close this now.

**Comment by jadlers** [comment]
Closing since this PR is replaced by #10 which includes all of these changes

**Pull request closed without merging**
